echo    Alpha Page 0...
tasmx -65 -b -y -s -fff -wmhtext.tab auxpgm_0.asm .\obj\auxpgm_0.obj .\lst\auxpgm_0.lst .\exp\auxpgm_0.exp .\sym\auxpgm_0.sym > auxpgm_0.err 

echo    Alpha Page 1...
tasmx -65 -b -y -s -fff auxpgm_1.asm .\obj\auxpgm_1.obj .\lst\auxpgm_1.lst .\exp\auxpgm_1.exp .\sym\auxpgm_1.sym > auxpgm_1.err

echo    Alpha Page 2...
tasmx -65 -b -y -s -fff auxpgm_2.asm .\obj\auxpgm_2.obj .\lst\auxpgm_2.lst .\exp\auxpgm_2.exp .\sym\auxpgm_2.sym > auxpgm_2.err

echo    Alpha Page 3...
tasmx -65 -b -y -s -fff -wmhtext.tab auxpgm_3.asm .\obj\auxpgm_3.obj .\lst\auxpgm_3.lst .\exp\auxpgm_3.exp .\sym\auxpgm_3.sym > auxpgm_3.err

echo    Alpha Page 4...
tasmx -65 -b -y -s -fff -wmhtext.tab auxpgm_4.asm .\obj\auxpgm_4.obj .\lst\auxpgm_4.lst .\exp\auxpgm_4.exp .\sym\auxpgm_4.sym > auxpgm_4.err

echo    Alpha Page 5...
tasmx -65 -b -y -s -fff auxpgm_5.asm .\obj\auxpgm_5.obj .\lst\auxpgm_5.lst .\exp\auxpgm_5.exp .\sym\auxpgm_5.sym > auxpgm_5.err

echo    Alpha Page 6...
tasmx -65 -b -y -s -fff auxpgm_6.asm .\obj\auxpgm_6.obj .\lst\auxpgm_6.lst .\exp\auxpgm_6.exp .\sym\auxpgm_6.sym > auxpgm_6.err

echo    Alpha Page 7...
tasmx -65 -b -y -s -fff auxpgm_7.asm .\obj\auxpgm_7.obj .\lst\auxpgm_7.lst .\exp\auxpgm_7.exp .\sym\auxpgm_7.sym > auxpgm_7.err

echo    Alpha Main...
tasmx -65 -b -y -s -fff mh_alpha.asm .\obj\mh_alpha.obj .\lst\mh_alpha.lst .\exp\mh_alpha.exp .\sym\mh_alpha.sym > mh_alpha.err
