;***********************************************
; Self Test Strings
; 
; FRENCH
;**********************************************
;************************** 
;Message Strings
;**************************
paux    .ctext "-'AUX': fCRAN SUIVANT"        
prshld  .ctext "-'ROLLER': MODIF. SELECTION"        
pfire   .ctext "-'FIRE': APPLIQUER" 
pshield .ctext "'SHIELD': CONFIRMER!!"        
gtest   .ctext "--- PROC. GAMMA  ---"        
atest   .ctext "--- PROC. ALPHA ---"  
btest   .ctext "--- PROC. BETA ---"      
gmstat  .ctext "--- STATS DU JEU ---"
inpout  .ctext "--- ENTRfES-SORTIES ---"
warpt   .ctext "--- RACCOURCIS ---"
act1pg  .ctext "JEU 1J: "
act2pg  .ctext "JEU 2J: "        
actwrps .ctext "RACCOURCIS: "        
actxliv .ctext "X VIES: "        
avggtim .ctext "TPS MOY.JEU"        
rstaths .ctext "RfINIT. SCORES"        
rstatgs .ctext "RfINIT. STATS"   
rstatop .ctext "RfINIT. PARAM. JEU"     
;ccl     .ctext "COMPTEUR GAUCHE PIeCES"        
;ccr     .ctext "COMPTEU DROIT PIeCES"         
soundof .ctext "SONS NON"
soundn  .ctext "SON OUI"                      
testra  .ctext "TESTS RAM:"        
testro  .ctext "TESTS ROM:"        
rammain .ctext "APRINC."    
brammain .ctext "BPRINC."      
ramswap .ctext "ASWAP"        
vectral .ctext "VBAS"        
vectrah .ctext "VHAUT"         
acomm    .ctext "ACOM"
bcomm    .ctext "BCOM"
mpass   .ctext "P"
mfail   .ctext "X"        
mnotuse .ctext "PAS UT."
romlow  .ctext "AL"         
romhig  .ctext "AH"   
bromlow .ctext "BL"         
bromhig .ctext "BH"       
rompg0  .ctext "AP0"        
rompg1  .ctext "AP1"        
rompg2  .ctext "AP2"
rompg3  .ctext "AP3"
rompg4  .ctext "AP4"        
rompg5  .ctext "AP5"  
rompg6  .ctext "AP6" 
rompg7  .ctext "AP7"
vectrom .ctext "VM"        
vectro0 .ctext "VP0"        
vectro1 .ctext "VP1"
vectro2 .ctext "VP2"
vectro3 .ctext "VP3"
vermiss .ctext "VERSION DISCORD."
testgde .ctext "TESTS MATfRIEL:"        
gammram .ctext "RAM PRINCIP.    " 
gammrom .ctext "ROM PRINCIP.     "        
gammpok .ctext "Q-POKEY      "       
gammeer .ctext "EEROM        "        
gamcmd  .ctext "ENV. CMDE POUR GAMMA:"
warpr   .ctext "ROUGE"
warpy   .ctext "JAUNE"
warpg   .ctext "VERT"
warpa   .ctext "'EAU'"
warpb   .ctext "BLEU"
warpp   .ctext "VIOLET"
warpk   .ctext "ROSE"
warp    .ctext "RACCOURCI:"
warpc   .ctext "CODE:"
warpn   .ctext "-"
gamad    .ctext "GAMMA INADfQUAT!"
gsetts    .ctext "--- PARAMeTRES DU JEU ---"
;pricin    .ctext "TARIF:"
;strlif    .ctext "NBR VIES INIT:"
;gamdif    .ctext "DIFFICULTf:"
;bonlif    .ctext "VIE BONUS:"
;attsnd    .ctext "SON 'ATTRACT':"
;adadif    .ctext "ADAPT. DFCTf:"
cfree   .ctext "PARTIES GRATUITES"
c1p1    .ctext "1 PIeCE 1 PARTIE"
c1p2    .ctext "1 PIeCE 2 PARTIES"
c2p1    .ctext "2 PIeCES 1 PARTIE"
livem    .ctext " VIE"
actc    .ctext "MODE DfMO"        
actd    .ctext "DIFF FAIBLE"        
acte    .ctext "DIFF MOY."        
actf    .ctext "DIFF fLEVfE" 
bon50    .ctext "BONUS a 50,000"
bon100  .ctext "BONUS a 100,000"
bon200    .ctext "BONUS a 200,000"
bonno    .ctext "PAS DE VIE BONUS"
;addon    .ctext "DIFF ADAPTATIVE OUI"
;addoff    .ctext "DIFF ADAPTATIVE NON"
rollx1	.ctext "ROLLER X 1"
rollx2	.ctext "ROLLER X 2"
sndon    .ctext "SONS ATT OUI"
sndoff    .ctext "SONS ATT NON"
lddips    .ctext "RfINIT TOUS COMMUT"  
firesel .ctext "-'FIRE': SELECT"   
rollsel .ctext "-ROLLER': CHANGER"   
pshelds .ctext "-'SHIELD': APPLIQUER!!"     
wmsg1    .ctext "< DfF RACCOURCIS CLASSIQ"
wmsg2    .ctext "< RACCOURCIS ALfATOIRE"
wmsg3    .ctext "< RfINIT. RACCOURCIS"
;wshlds    .ctext "'SHIELD': APPLIQUER"




; paux    .ctext "-'AUX': fCRAN SUIVANT"        
; prshld  .ctext "-'ROLLER': MODIF. SELECTION"        
; pfire   .ctext "-'FIRE': APPLIQUER" 
; pshield .ctext "'SHIELD': CONFIRMER!!"        
; gtest   .ctext "--- PROC. GAMMA  ---"         
; atest   .ctext "--- PROC. ALPHA ---" 
; btest   .ctext "--- PROC. BETA ---"      
; gmstat  .ctext "--- STATS DU JEU ---"
; inpout  .ctext "--- ENTRfES-SORTIES ---"
; warpt   .ctext "--- RACCOURCIS ---"
; act1pg  .ctext "JEUX 1J: "
; act2pg  .ctext "JEUX 2J: "        
; actwrps .ctext "RACCOURCIS: "        
; actxliv .ctext "XVIES: "        
; avggtim .ctext "TPS JEU MOYEN "        
; rstaths .ctext "RfINIT. SCORES"        
; rstatgs .ctext "RfINIT. STATS"   
; rstatop .ctext "RfINIT. PARAM. JEU"     
; ;ccl     .ctext "COMPTEUR GAUCHE PIeCES"        
; ;ccr     .ctext "COMPTEUR DROIT PIeCES"         
; soundof .ctext "SONS NON"
; soundn  .ctext "SON OUI"                      
; testra  .ctext "TESTS RAM:"        
; testro  .ctext "TESTS ROM:"        
; rammain .ctext "APRINC."    
; brammain .ctext "BPRINC."      
; ramswap .ctext "ASWAP"        
; vectral .ctext "VBAS"        
; vectrah .ctext "VHAUT"         
; acomm    .ctext "ACOM"
; bcomm    .ctext "BCOM"
; mpass   .ctext "P"
; mfail   .ctext "X"        
; mnotuse .ctext "PAS UT."
; romlow  .ctext "AL"         
; romhig  .ctext "AH"   
; bromlow .ctext "BL"         
; bromhig .ctext "BH"       
; rompg0  .ctext "AP0"        
; rompg1  .ctext "AP1"        
; rompg2  .ctext "AP2"
; rompg3  .ctext "AP3"
; rompg4  .ctext "AP4"        
; rompg5  .ctext "AP5"  
; rompg6  .ctext "AP6" 
; rompg7  .ctext "AP7"
; vectrom .ctext "VM"        
; vectro0 .ctext "VP0"        
; vectro1 .ctext "VP1"
; vectro2 .ctext "VP2"
; vectro3 .ctext "VP3"
; vermiss .ctext "VERSION DISCORD."
; testgde .ctext "TESTS MATfRIEL:"        
; gammram .ctext "RAM PRINCIP.    " 
; gammrom .ctext "ROM PRINCIP.     "        
; gammpok .ctext "Q-POKEY      "       
; gammeer .ctext "EEROM        "        
; gamcmd  .ctext "ENV. CMDE POUR GAMMA:"
; warpr   .ctext "ROUGE"
; warpy   .ctext "JAUNE"
; warpg   .ctext "VERT"
; warpa   .ctext "'EAU'"
; warpb   .ctext "BLEU"
; warpp   .ctext "VIOLET"
; warpk   .ctext "ROSE"
; warp    .ctext "RACCOURCI:"
; warpc   .ctext "CODE:"
; warpn   .ctext "-"
; gamad    .ctext "GAMMA INADfQUAT!"
; gsetts    .ctext "--- PARAMeTRES DU JEU ---"

; ;pricin    .ctext "TARIF:"
; ;strlif    .ctext "NBR VIES INIT:"
; ;gamdif    .ctext "DIFFICULTf:"
; ;bonlif    .ctext "VIE BONUS:"
; ;attsnd    .ctext "SON 'ATTRACT':"
; ;adadif    .ctext "ADAPT. DFCTf:"

; cfree   .ctext "PARTIES GRATUITES"
; c1p1    .ctext "1 PIeCE 1 PARTIE"
; c1p2    .ctext "1 PIeCE 2 PARTIES"
; c2p1    .ctext "2 PIeCES 1 PARTIE"

; livem   .ctext " VIE"
; actc    .ctext "MODE DfMO"        
; actd    .ctext "DIFF FAIBLE"        
; acte    .ctext "DIFF MOY"        
; actf    .ctext "DIFF fLEVfE" 
; bon50   .ctext "BONUS a 50K"
; bon100  .ctext "BONUS a 100K"
; bon200  .ctext "BONUS a 200K"
; bonno   .ctext "PAS DE VIE BONUS"
; rollx1	.ctext "ROLLER X 1"
; rollx2	.ctext "ROLLER X 2"
; ;addon   .ctext "DIFF ADAPTATIVE OUI"
; ;addoff  .ctext "DIFF ADAPTATIVE NON"
; sndon   .ctext "SONS ATT OUI"
; sndoff  .ctext "SONS ATT NON"
; lddips  .ctext "RfINIT TOUS COMMUT"  
; firesel .ctext "-'FIRE': SELECT"   
; rollsel .ctext "-ROLLER': CHANGER"  
; pshelds .ctext "-'SHIELD': APPLIQUER!!"      
; wmsg1   .ctext "< DfF RACCOURCIS CLASSIQ"
; wmsg2   .ctext "< ALeATOIRE RACCOURCIS"
; ;wmsg3   .ctext "< RfINIT. RACCOURCIS"
; ;wshlds   .ctext "'SHIELD' POUR APPLIQUER"




