;***********************************************
; Self Test Strings
; 
; GERMAN
;**********************************************

paux    .ctext "-AUX FOR NEXT SCREEN"        
prshld  .ctext "-ROLLER TO CHANGE"        
pfire   .ctext "-FIRE TO APPLY" 
pshield .ctext "SHIELD TO CONFIRM!!"        
gtest   .ctext "--- GAMMA CPU ---"        
atest   .ctext "--- ALPHA CPU ---"  
btest   .ctext "--- BETA CPU ---"      
gmstat  .ctext "--- GAME STATISTICS ---"
inpout  .ctext "--- INPUTSsOUTPUTS ---"
warpt   .ctext "--- WARPS ---"
act1pg  .ctext "1P GAMES: "
act2pg  .ctext "2P GAMES: "        
actwrps .ctext "WARPS: "        
actxliv .ctext "XLIVES: "        
avggtim .ctext "AVG GAME TIME "        
rstaths .ctext "RESET SCORES"        
rstatgs .ctext "RESET STATS"   
rstatop .ctext "RESET GAME OPTIONS"     
;ccl     .ctext "COIN COUNTER LEFT"        
;ccr     .ctext "COIN COUNTER RIGHT"         
soundof .ctext "SOUNDS OFF"
soundn  .ctext "SOUND "                      
testra  .ctext "RAM TESTS:"        
testro  .ctext "ROM TESTS:"        
rammain .ctext "AMAIN"    
brammain .ctext "BMAIN"      
ramswap .ctext "ASWAP"        
vectral .ctext "VLOW"        
vectrah .ctext "VHIGH"         
acomm 	.ctext "ACOM"
bcomm	.ctext "BCOM"
mpass   .ctext "P"
mfail   .ctext "X"        
mnotuse .ctext "NOT USED"
romlow  .ctext "AL"         
romhig  .ctext "AH"   
bromlow .ctext "BL"         
bromhig .ctext "BH"       
rompg0  .ctext "AP0"        
rompg1  .ctext "AP1"        
rompg2  .ctext "AP2"
rompg3  .ctext "AP3"
rompg4  .ctext "AP4"        
rompg5  .ctext "AP5"  
rompg6  .ctext "AP6" 
rompg7  .ctext "AP7"
vectrom .ctext "VM"        
vectro0 .ctext "VP0"        
vectro1 .ctext "VP1"
vectro2 .ctext "VP2"
vectro3 .ctext "VP3"
vermiss .ctext "VERSION MISMATCH"
testgde .ctext "DEVICE TESTS:"        
gammram .ctext "MAIN RAM     " 
gammrom .ctext "MAIN ROM     "        
gammpok .ctext "Q-POKEY      "       
gammeer .ctext "EEROM        "        
gamcmd  .ctext "SEND COMMAND TO GAMMA:"
warpr   .ctext "RED"
warpy   .ctext "YELLOW"
warpg   .ctext "GREEN"
warpa   .ctext "AQUA"
warpb   .ctext "BLUE"
warpp   .ctext "PURPLE"
warpk   .ctext "PINK"
warp    .ctext "WARP:"
warpc   .ctext "CODE:"
warpn   .ctext "-"
gamad	.ctext "GAMMA BAD!"

gsetts 	.ctext "--- GAME SETTINGS ---"
;pricin	.ctext "PRICING:"
;strlif	.ctext "STARTING LIVES:"
;gamdif	.ctext "DIFFICULTY:"
;bonlif	.ctext "BONUS LIFE:"
;attsnd	.ctext "ATTRACT SOUND:"
;adadif	.ctext "ADAPT. DFCTY:"

cfree   .ctext "FREE PLAY"
c1p1	.ctext "1 COIN 1 PLAY"
c1p2	.ctext "1 COIN 2 PLAYS"
c2p1	.ctext "2 COINS 1 PLAY"

livem	.ctext " LIVES"
actc    .ctext "DEMO MODE"        
actd    .ctext "EASY DIFF"        
acte    .ctext "MEDIUM DIFF"        
actf    .ctext "HARD DIFF" 
bon50	.ctext "BONUS @ 50K"
bon100  .ctext "BONUS @ 100K"
bon200	.ctext "BONUS @ 200K"
bonno	.ctext "NO BONUS LIFE"
rollx1	.ctext "ROLLER X 1"
rollx2	.ctext "ROLLER X 2"
; addon	.ctext "ADAPTIVE DIFF ON"
; addoff	.ctext "ADAPTIVE DIFF OFF"
sndon	.ctext "ATT SNDS ON"
sndoff	.ctext "ATT SNDS OFF"

lddips	.ctext "RESET ALL TO DIPS"  
firesel .ctext "-FIRE TO SELECT"   
rollsel .ctext "-ROLLER TO CHANGE"   
pshelds .ctext "-SHIELD TO APPLY!!"     
wmsg1	.ctext "< SET CLASSIC WARPS"
wmsg2	.ctext "< RANDOM WARPS"
;wmsg3	.ctext "< RESET WARPS"
;wshlds	.ctext "-SHIELD TO APPLY"